nameOverride: atm-fraud-accountlinker

replicaCount: 1

image: bakdata/atm-demo-accountlinker
imageTag: latest

kafka:
  bootstrapServers: "kafka://my-confluent-cp-kafka-headless:9092"
  schemaRegistryUrl: "http://my-confluent-cp-schema-registry:8081"
  inputTopics:
    - atm-fraud-possiblefraudtransactions-topic
  labeledInputTopics:
    accounts:
      - atm-fraud-accounts-topic
  outputTopic: atm-fraud-output-topic
  errorTopic: atm-fraud-accountlinker-error-topic

annotations:
  consumerGroup: "streams-explorer-accountlinker-atm-fraud-output-topic"

prometheus:
  jmx:
    enabled: false
